### PR TITLE
Feature 497

### PR DESCRIPTION
**Pull request by FredKF**
# PR Details

Creating a new slider component with double inputs.

## Description

This component is used to specify a minimum and maximum value dynamically. It is based on the already existing slider component.

As it will be used in some forms, the best approach was to create a brand new component that fulfills the needs of the form.

## Related Issue

https://github.com/systelab/systelab-components/issues/497

## Motivation and Context

The new component needed in specific forms will provide a range that can be selected dynamically.

## How Has This Been Tested

The unit testing strategy used was to create a totally isolated component as a mock of the original component and the main idea is to test that values are representing a range.

Tested with Jasmine

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation 
- [x] I have updated the documentation accordingly (README.md for each UI component)
- [x] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [x] All new and existing tests passed
- [x] A new branch needs to be created from master to evolve previous versions
- [x] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [x] All UI components must be added into the showcase (at least 1 component with the default settings)
- [x] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

### CODE REVIEW

**Review by alfonsserra — DISMISSED** [review]
Thank you very much. Good implementation. Remember to add some reviewers!!!!

My only comment is related to styles and if it is possible to have a style when the component is focused (with the tab). Please see the regular slider as example.

**Comment by FredKF** [comment]
> Thank you very much. Good implementation. Remember to add some reviewers!!!!
> 
> My only comment is related to styles and if it is possible to have a style when the component is focused (with the tab). Please see the regular slider as example.

Thanks Alfons, I'll take a look about that focus styling.

**Review by carlosra85 — COMMENTED** [review]
I see everything is fine. Good job! But I think you have an strange formatter for templates, new and old ones are reformatted weird

**Comment by FredKF** [comment]
> I see everything is fine. Good job! But I think you have an strange formatter for templates, new and old ones are reformatted weird

Hello Carlos, thanks for your comment, I use Prettier as a formatter but this is a personal preference, do you use a standard one for all templates ? , thanks!

**Comment by carlosra85** [comment]
> > I see everything is fine. Good job! But I think you have an strange formatter for templates, new and old ones are reformatted weird
> 
> Hello Carlos, thanks for your comment, I use Prettier as a formatter but this is a personal preference, do you use a standard one for all templates ? , thanks!

We don't have an standard, and in fact using Prettier had been discussed in the past but it was not materialized. In your case I think lanes are too short in Prettier default, we usually have single line tags

**Review by carlosra85 — DISMISSED** [review]

**Review by oGalceran1 — APPROVED** [review]

**Review by apenalver2 — APPROVED** [review]
Thank you!!!

**Review by alfonsserra — DISMISSED** [review]
Great PR!!!

**Review by oGalceran1 — APPROVED** [review]

**Review by carlosra85 — APPROVED** [review]

**Review by abeliuss — APPROVED** [review]

**Pull request merged**
