### PR TITLE
#442 include-numpaddecimalnumericdirective

### PR DESCRIPTION
**Pull request by pepgrifell**
# PR Details

Added a directive to put the decimal separator according to the locale when pressed the "." in the numpad keyboard.

## Description

Added NumpadDecimalNumericDirective and tests.

## Motivation and Context

In some places, the numpad decimal separator should be locale reactive, in the sense that in Spanish, the "." should be changed by the ","

## How Has This Been Tested

Added unit tests

## Types of changes

- [X] Docs change / refactoring / dependency upgrade
- [-] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [-] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] I have read the **CONTRIBUTING** document
- [X] My code follows the code style of this project
- [X] My change requires a change to the documentation 
- [X] I have updated the documentation accordingly (README.md for each UI component)
- [X] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [X] All new and existing tests passed
- [-] A new branch needs to be created from master to evolve previous versions
- [X] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [-] All UI components must be added into the showcase (at least 1 component with the default settings)
- [-] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

### CODE REVIEW

**Comment by olgapuig** [comment]
@pepgrifell do you need this functionality in Angularv12? The master is already in Angularv14

**Comment by pepgrifell** [comment]
> @pepgrifell do you need this functionality in Angularv12? The master is already in Angularv14

No, it's for v14. We already have this directive in Anthema but we will remove it when the library will have it.

**Review by diegocj28 — APPROVED** [review]
Great job! Thanks @pepgrifell

**Review by oGalceran1 — APPROVED** [review]
Thanks

**Review by rochiebcn — APPROVED** [review]
Thank you pep!

**Pull request merged**
