### PR TITLE
Modifications in the Combobox and fix Signature Canvas 

### PR DESCRIPTION
**Pull request by apenalver2**
Combobox

- Add Select All and Deselect All buttons
- Add the 'selected' attribute in the values list (multiple combobox)
- If the id is informed, the description in the combobox will be the description of the selected value.

Signature Canvas

- Fix the return button

### CODE REVIEW

**Comment by vinyulis** [comment]
I added a commit:

Changes in select/Deselect all:

- Use a button group
- Button group has a width of 100%
- Changed Input name. Before: allValues --> Now: selectDeselectAll


Moved initialization of selected values to ngOnInit but this code must be removed due to it should be done using [id] and [description] or [(id)] and [(description)]. Also for multiple selection, it should be developed as in abstract-api-combobox.

**Comment by vinyulis** [comment]
@apenalver2, what do you think about the changes done in select/deselect all?

Can you remove the initialization of selected values on ngOnInit and do it as in abstract-api-combobox?

**Comment by apenalver2** [comment]
@vinyulis What are you referring "do it as in abstract-api-combobox"? in the api of "GridApi" interface, the unique method that seems to be used for this intended is "selectIndex". Are you refering to use this way?

If we use the id to define the selected values in the multiple selection, we will need to define the id parameter from  "number | string" to "number | string | Array".

**Comment by alfonsserra** [comment]
@apenalver2 I do not understand the comment from @vinyulis. Hopefully he will clarify his point.

**Comment by vinyulis** [comment]
@aserra I have been talking with @apenalver2 about this. 

Multiple selection is developed in abstract-api-combobox but not in the parent class abstract-combobox. @apenalver2 has developed multiple selection in abstract-combobox without knowing the existance of the inheritance (also others, like tree or autocomplete) and maybe he needs to use abstract-api-combobox instead of abstract-combobox. If we want to develop this at abstract-combobox level we will need to refactor at least abstract-api-combox and pull up multiple selection there.

About the initialization of selected values in the combo field I suggested not to do it in ngOnInit because in abstract-api-combobox could happen that not all the values are loaded in the combo (because is a paginated one). After developing some comboboxes using abstract-api-combobox we initialize directly in the template, maintaining the model of the view with the two way binding.

Example in combobox:

`<mp-doctor-mixed-autocomplete-combobox class="d-flex w-100 h-100"
                                                       *ngSwitchCase="element.name==='doctor-mixed'"
                                                       [(id)]="request.doctorID"
                                                       [(code)]="request.collegiateID"
                                                       [(description)]="request.doctorName"/>` 

Example in multiple combobox:

`<mp-diagnosis-combobox class="d-flex w-100 h-100"
                                       [(multipleSelectedItemList)]="diagnosisList/>`

We need to think the best way to refactor this if needed.

I hope I have explained it better.

**Pull request merged**
