### PR TITLE
Add the option "don't ask again" in the message box #632

### PR DESCRIPTION
**Pull request by diegocj28**
# PR Details

Modify the message box to allow introducing a check within the modal.

## Description

A new instance of the message box has been created to display a check within the popup.

## Related Issue

#632 

## Motivation and Context

This implemented change improves the user experience in those cases where the same popup is always displayed.

## How Has This Been Tested

Automatic test
Manual test launching
Creating a showcase application

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X ] I have read the **CONTRIBUTING** document
- [X] My code follows the code style of this project
- [X] My change requires a change to the documentation 
- [X] I have updated the documentation accordingly (README.md for each UI component)
- [X] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [X] All new and existing tests passed
- [X] A new branch needs to be created from master to evolve previous versions
- [X] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [X] All UI components must be added into the showcase (at least 1 component with the default settings)
- [X] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

### CODE REVIEW

**Review by pepgrifell — DISMISSED** [review]
It seems ok to me. Thanks!

**Review by rochiebcn — DISMISSED** [review]
Great!! Thank you Diego!

**Review by jjdelsar — DISMISSED** [review]
Good job! Thanks!

**Review by rochiebcn — APPROVED** [review]
Reviewed again. Thank you

**Review by pepgrifell — APPROVED** [review]
revised

**Review by jjdelsar — APPROVED** [review]

**Pull request merged**
